import {SAMPLE_CSV} from "../../src/demo/sample-csv";

/**
 * The sample export, downloadable.
 *
 * Served from the embedded module rather than a file in public/, for the same
 * reason the owner button uses it: one copy, generated by one script, so the
 * file someone downloads and the ledger the button loads can never drift apart.
 *
 * Public on purpose. It is synthetic — no real company, no real bank account —
 * and someone deciding whether their own export will work needs to see the
 * shape before they hand over their accounts payable.
 */
export function GET() {
  return new Response(SAMPLE_CSV, {
    headers: {
      "content-type": "text/csv; charset=utf-8",
      "content-disposition": 'attachment; filename="countercheck-sample.csv"',
      "cache-control": "public, max-age=3600",
    },
  });
}
